
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 20-Feb-24 8:30:39 AM.
      Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.72
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 20-Feb-24 8:30:40 AM.
      Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.49
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-n3k5a3"
      binary: "D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-n3k5a3"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-n3k5a3'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_a1fea.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 20-Feb-24 8:30:40 AM.
        Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-n3k5a3\\cmTC_a1fea.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_a1fea.dir\\Debug\\".
          Creating directory "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-n3k5a3\\Debug\\".
          Creating directory "cmTC_a1fea.dir\\Debug\\cmTC_a1fea.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_a1fea.dir\\Debug\\cmTC_a1fea.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a1fea.dir\\Debug\\\\" /Fd"cmTC_a1fea.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a1fea.dir\\Debug\\\\" /Fd"cmTC_a1fea.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-n3k5a3\\Debug\\cmTC_a1fea.exe" /INCREMENTAL /ILK:"cmTC_a1fea.dir\\Debug\\cmTC_a1fea.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-n3k5a3/Debug/cmTC_a1fea.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-n3k5a3/Debug/cmTC_a1fea.lib" /MACHINE:X64  /machine:x64 cmTC_a1fea.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_a1fea.vcxproj -> D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-n3k5a3\\Debug\\cmTC_a1fea.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_a1fea.dir\\Debug\\cmTC_a1fea.tlog\\unsuccessfulbuild".
          Touching "cmTC_a1fea.dir\\Debug\\cmTC_a1fea.tlog\\cmTC_a1fea.lastbuildstate".
        Done Building Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-n3k5a3\\cmTC_a1fea.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.45
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-6tizb7"
      binary: "D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-6tizb7"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-6tizb7'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_5a707.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 20-Feb-24 8:30:41 AM.
        Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-6tizb7\\cmTC_5a707.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_5a707.dir\\Debug\\".
          Creating directory "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-6tizb7\\Debug\\".
          Creating directory "cmTC_5a707.dir\\Debug\\cmTC_5a707.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_5a707.dir\\Debug\\cmTC_5a707.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5a707.dir\\Debug\\\\" /Fd"cmTC_5a707.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30151 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5a707.dir\\Debug\\\\" /Fd"cmTC_5a707.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-6tizb7\\Debug\\cmTC_5a707.exe" /INCREMENTAL /ILK:"cmTC_5a707.dir\\Debug\\cmTC_5a707.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-6tizb7/Debug/cmTC_5a707.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Tutorial/cmake-3.29.0-rc1-tutorial-source/Step1/Step1_build/CMakeFiles/CMakeScratch/TryCompile-6tizb7/Debug/cmTC_5a707.lib" /MACHINE:X64  /machine:x64 cmTC_5a707.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_5a707.vcxproj -> D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-6tizb7\\Debug\\cmTC_5a707.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_5a707.dir\\Debug\\cmTC_5a707.tlog\\unsuccessfulbuild".
          Touching "cmTC_5a707.dir\\Debug\\cmTC_5a707.tlog\\cmTC_5a707.lastbuildstate".
        Done Building Project "D:\\Tutorial\\cmake-3.29.0-rc1-tutorial-source\\Step1\\Step1_build\\CMakeFiles\\CMakeScratch\\TryCompile-6tizb7\\cmTC_5a707.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.46
        
      exitCode: 0
...
